// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyrxtqaccmrfvspcfhjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5cnh0cWFjY21yZnZzcGNmaGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzY5MDQsImV4cCI6MjA2NTkxMjkwNH0.y7pwI3YIOO0EsuBMGa71LlqQijJezykhLyuMh-hbxMY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);